const WORK_SCHEDULE = Object.freeze({
  NIGHT_AND_MORNING: '00:01-09:00',
  MORNING_AND_EVENING: '09:01-18:00',
  EVENING_AND_NIGHT: '18:01-23:59',
});

const HOUR_PAYMENT = Object.freeze({
  NIGHT_AND_MORNING: 25,
  MORNING_AND_EVENING: 15,
  EVENING_AND_NIGHT: 20,
});

const EXTRA_BONUS_WEEKEND = 5;

module.exports = {
  WORK_SCHEDULE,
  HOUR_PAYMENT,
  EXTRA_BONUS_WEEKEND
};
